src/main/java/org/zdd/bookstore/model/entity/Orders.java
package org.zdd.bookstore.model.entity;

import java.util.Date;
import javax.persistence.*;

@Table(name = "orders")
public class Orders {
    /**
     * 订单id
     */
    @Id
    @Column(name = "order_id")
    private String orderId;

    /**
     * 用户id
     */
    @Column(name = "user_id")
    private Integer userId;

    /**
     * 实付金额。精确到2位小数;单位:元。如:200.07，表示:200元7分
     */
    @Column(name = "payment")
    private String payment;

    /**
     * 支付类型，1、微信，2、支付宝
     */
    @Column(name = "payment_type")
    private Integer paymentType;

    /**
     * 支付状态 0未支付 1已支付
     */
    @Column(name = "status")
    private Integer status;

    /**
     * 邮费。精确到2位小数;单位:元。如:200.07，表示:200元7分
     */
    @Column(name = "post_fee")
    private String postFee;

    /**
     * 订单创建时间
     */
    @Column(name = "create_time")
    private Date createTime;

    /**
     * 订单更新时间
     */
    @Column(name = "update_time")
    private Date updateTime;

    @Column(name = "order_mount")
    private Integer orderMount;

    /**
     * 付款时间
     */
    @Column(name = "payment_time")
    private Date paymentTime;

    /**
     * 交易完成时间
     */
    @Column(name = "end_time")
    private Date endTime;

    /**
     * 交易关闭时间
     */
    @Column(name = "close_time")
    private Date closeTime;

    /**
     * 物流名称
     */
    @Column(name = "shipping_name")
    private String shippingName;

    /**
     * 物流单号
     */
    @Column(name = "shipping_code")
    private String shippingCode;

    /**
     * 买家留言
     */
    @Column(name = "buyer_message")
    private String buyerMessage;

    /**
     * 买家是否已经评价
     */
    @Column(name = "buyer_rate")
    private Integer buyerRate;

    /**
     * 获取订单id
     *
     * @return order_id - 订单id
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * 设置订单id
     *
     * @param orderId 订单id
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * 获取用户id
     *
     * @return user_id - 用户id
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * 设置用户id
     *
     * @param userId 用户id
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * 获取实付金额。精确到2位小数;单位:元。如:200.07，表示:200元7分
     *
     * @return payment - 实付金额。精确到2位小数;单位:元。如:200.07，表示:200元7分
     */
    public String getPayment() {
        return payment;
    }

    /**
     * 设置实付金额。精确到2位小数;单位:元。如:200.07，表示:200元7分
     *
     * @param payment 实付金额。精确到2位小数;单位:元。如:200.07，表示:200元7分
     */
    public void setPayment(String payment) {
        this.payment = payment == null ? null : payment.trim();
    }

    /**
     * 获取支付类型，1、在线支付，2、货到付款
     *
     * @return payment_type - 支付类型，1、在线支付，2、货到付款
     */
    public Integer getPaymentType() {
        return paymentType;
    }

    /**
     * 设置支付类型，1、微信，2、支付宝
     *
     * @param paymentType 支付类型，1、微信，2、支付宝
     */
    public void setPaymentType(Integer paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * 获取订单状态：0、未付款，1、已付款，2、未发货，3、已发货，4、确认收货，5、交易关闭
     *
     * @return status - 状态：0、未付款，1、已付款，2、未发货，3、已发货，4、确认收货，5、交易关闭
     */
    public Integer getStatus() {
        return status;
    }

    public String getStatusString(){
        if(status == 0){
            return "未付款";
        }else if(status == 1){
            return "已付款";
        }else if(status == 2){
            return "未发货";
        }else if(status == 3){
            return "已发货";
        }else if(status == 4){
            return "确认收货";
        }else{
            return "交易关闭";
        }
    }

    /**
     * 设置支付状态 未付款，1、已付款，2、未发货，3、已发货，4、确认收货，5、交易关闭
     *
     * @param status 支付状态 1、已付款，2、未发货，3、已发货，4、确认收货，5、交易关闭
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 获取邮费。精确到2位小数;单位:元。如:200.07，表示:200元7分
     *
     * @return post_fee - 邮费。精确到2位小数;单位:元。如:200.07，表示:200元7分
     */
    public String getPostFee() {
        return postFee;
    }

    /**
     * 设置邮费。精确到2位小数;单位:元。如:200.07，表示:200元7分
     *
     * @param postFee 邮费。精确到2位小数;单位:元。如:200.07，表示:200元7分
     */
    public void setPostFee(String postFee) {
        this.postFee = postFee == null ? null : postFee.trim();
    }

    /**
     * 获取订单创建时间
     *
     * @return create_time - 订单创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置订单创建时间
     *
     * @param createTime 订单创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取订单更新时间
     *
     * @return update_time - 订单更新时间
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 设置订单更新时间
     *
     * @param updateTime 订单更新时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * @return order_mount
     */
    public Integer getOrderMount() {
        return orderMount;
    }

    /**
     * @param orderMount
     */
    public void setOrderMount(Integer orderMount) {
        this.orderMount = orderMount;
    }

    /**
     * 获取付款时间
     *
     * @return payment_time - 付款时间
     */
    public Date getPaymentTime() {
        return paymentTime;
    }

    /**
     * 设置付款时间
     *
     * @param paymentTime 付款时间
     */
    public void setPaymentTime(Date paymentTime) {
        this.paymentTime = paymentTime;
    }

    /**
     * 获取交易完成时间
     *
     * @return end_time - 交易完成时间
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * 设置交易完成时间
     *
     * @param endTime 交易完成时间
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * 获取交易关闭时间
     *
     * @return close_time - 交易关闭时间
     */
    public Date getCloseTime() {
        return closeTime;
    }

    /**
     * 设置交易关闭时间
     *
     * @param closeTime 交易关闭时间
     */
    public void setCloseTime(Date closeTime) {
        this.closeTime = closeTime;
    }

    /**
     * 获取物流名称
     *
     * @return shipping_name - 物流名称
     */
    public String getShippingName() {
        return shippingName;
    }

    /**
     * 设置物流名称
     *
     * @param shippingName 物流名称
     */
    public void setShippingName(String shippingName) {
        this.shippingName = shippingName == null ? null : shippingName.trim();
    }

    /**
     * 获取物流单号
     *
     * @return shipping_code - 物流单号
     */
    public String getShippingCode() {
        return shippingCode;
    }

    /**
     * 设置物流单号
     *
     * @param shippingCode 物流单号
     */
    public void setShippingCode(String shippingCode) {
        this.shippingCode = shippingCode == null ? null : shippingCode.trim();
    }

    /**
     * 获取买家留言
     *
     * @return buyer_message - 买家留言
     */
    public String getBuyerMessage() {
        return buyerMessage;
    }

    /**
     * 设置买家留言
     *
     * @param buyerMessage 买家留言
     */
    public void setBuyerMessage(String buyerMessage) {
        this.buyerMessage = buyerMessage == null ? null : buyerMessage.trim();
    }

    /**
     * 获取买家是否已经评价
     *
     * @return buyer_rate - 买家是否已经评价
     */
    public Integer getBuyerRate() {
        return buyerRate;
    }

    /**
     * 设置买家是否已经评价
     *
     * @param buyerRate 买家是否已经评价
     */
    public void setBuyerRate(Integer buyerRate) {
        this.buyerRate = buyerRate;
    }
}

src/main/java/org/zdd/bookstore/web/controller/OrderController.java
package org.zdd.bookstore.web.controller;

import org.zdd.bookstore.common.pojo.BSResult;
import org.zdd.bookstore.exception.BSException;
import org.zdd.bookstore.model.entity.BookInfo;
import org.zdd.bookstore.model.entity.custom.Cart;
import org.zdd.bookstore.model.entity.User;
import org.zdd.bookstore.model.entity.custom.OrderCustom;
import org.zdd.bookstore.model.service.IBookInfoService;
import org.zdd.bookstore.model.service.ICartService;
import org.zdd.bookstore.model.service.IOrderService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpServletRequest;
import java.util.List;

@Controller
@RequestMapping("/order")
public class OrderController {


    @Autowired
    private IOrderService orderService;

    @Autowired
    private ICartService cartService;

    @Autowired
    private IBookInfoService bookInfoService;

    /**
     * 填写订单信息页面
     *
     * @param bookId
     * @param buyNum
     * @param request
     * @return
     */
    @GetMapping("/info")
    public String orderInfo(@RequestParam(required = false, defaultValue = "0") int bookId,
                            @RequestParam(required = false, defaultValue = "0") int buyNum,
                            HttpServletRequest request) throws BSException {

        if (bookId != 0) {
            //点了立即购买，放到request域中，也session的立即购买域中以区分购物车中的书籍
            BookInfo bookInfo = bookInfoService.findById(bookId);
            if (bookInfo != null) {
                BSResult bsResult = cartService.addToCart(bookInfo, null, buyNum);
                request.getSession().setAttribute("buyNowCart", bsResult.getData());
                request.setAttribute("cart", bsResult.getData());
                return "order_info";
            } else {
                request.setAttribute("exception", "不好意思，书籍库存不足或不存在了！");
                return "exception";
            }
        }
        //没有点立即购买，购物车中的总金额大于0才让填写订单信息
        Cart cart = (Cart) request.getSession().getAttribute("cart");
        if (cart != null && cart.getTotal() > 0) {
            return "order_info";
        } else {
            return "cart";
        }


    }

    @GetMapping("/payPage/{orderId}")
    public String toPay(@PathVariable("orderId") String orderId, Model model) {

        BSResult bsResult = orderService.findOrderById(orderId);

        if (bsResult.getCode() == 200) {
            model.addAttribute("order", bsResult.getData());
            return "payment";
        }
        return "exception";
    }

    @RequestMapping("/deletion/{orderId}")
    public String deletion(@PathVariable("orderId") String orderId) {

        BSResult bsResult = orderService.deleteOrder(orderId);

        if (bsResult.getCode() == 200) {
            return "redirect:/order/list";
        }
        return "exception";
    }

    /**
     * 订单列表
     *
     * @return
     */
    @GetMapping("/list")
    public String orderList(HttpServletRequest request) {

        User loginUser = (User) request.getSession().getAttribute("loginUser");

        List<OrderCustom> orderCustoms = orderService.findOrdersByUserId(loginUser.getUserId());

        request.setAttribute("orderCustoms", orderCustoms);

        return "order_list";
    }

    /**
     * 创建订单
     *
     * @return
     */
    @PostMapping("/creation")
    public String createOrder(User userDTO, String express, int payMethod, HttpServletRequest request) {

        //立即购买,优先创建订单
        Cart buyNowCart = (Cart) request.getSession().getAttribute("buyNowCart");

        User loginUser = (User) request.getSession().getAttribute("loginUser");
        userDTO.setUserId(loginUser.getUserId());
        userDTO.setZipCode(loginUser.getZipCode());

        if (buyNowCart != null) {
            BSResult bsResult = orderService.createOrder(buyNowCart, userDTO, express, payMethod);

            if (bsResult.getCode() == 200) {
                request.setAttribute("order", bsResult.getData());
                cartService.clearCart(request, "buyNowCart");
                return "payment";
            } else {
                request.setAttribute("exception", bsResult.getMessage());
                return "exception";
            }
        }

        //普通购物车
        Cart cart = (Cart) request.getSession().getAttribute("cart");
        if (cart != null) {
            BSResult bsResult = orderService.createOrder(cart, userDTO, express, payMethod);

            if (bsResult.getCode() == 200) {
                request.setAttribute("order", bsResult.getData());
                cartService.clearCart(request, "cart");
                return "payment";
            } else {
                request.setAttribute("exception", bsResult.getMessage());
                return "exception";
            }

        } else {
            request.setAttribute("exception", "购物车为空！");
            return "exception";
        }

    }

    /**
     * 确认收货
     *
     * @param orderId
     * @return
     */
    @RequestMapping("/confirm/{orderId}")
    public String confirmReceiving(@PathVariable("orderId") String orderId, Model model) {
        BSResult bsResult = orderService.confirmReceiving(orderId);

        if (bsResult.getCode() == 200) {
            return "redirect:/order/list";
        } else {
            model.addAttribute("exception", bsResult.getMessage());
            return "exception";
        }

    }
}

src/main/webapp/WEB-INF/jsp/admin/order/edit.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%
    String path = request.getContextPath();
    String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + path + "/";
%>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title></title>
    <base href="<%=basePath%>">
    <script type="text/javascript" src="js/jquery-1.11.3.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.js"></script>
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <script type="text/javascript" src="js/jquery.validate.js"></script>
    <link rel="stylesheet" href="css/bs.css"/>
    <script type="text/javascript">

        $(function () {

            jQuery.validator.addMethod("isMobile", function (value, element) {
                var length = value.length;
                var mobile = /^(13[0-9]{9})|(18[0-9]{9})|(14[0-9]{9})|(17[0-9]{9})|(15[0-9]{9})$/;
                return this.optional(element) || (length == 11 && mobile.test(value));
            }, "请正确填写手机号码");

            $("#orderForm").validate({
                //一失去焦点就校验
                onfocusout: function (element) {
                    $(element).valid();
                },
                errorPlacement: function (error, element) {	//错误信息位置设置方法
                    error.appendTo(element.parent().next());//这里的error是生成的错误对象，element是录入数据的对象,parent父元素，next()下一个
                },
                errorClass: "red",
                rules: {
                    shippingName: {
                        required: true
                    },
                    receiverAddress: {
                        required: true
                    },
                    receiverName: {
                        required: true
                    },
                    receiverMobile: {
                        required: true,
                        isMobile:true
                    }
                },
                messages: {
                    shippingName: {
                        required: "请选择快递"
                    },
                    receiverAddress: {
                        required: "请填写收获地址"
                    },
                    receiverName: {
                        required: "请填写收货人姓名"
                    },
                    receiverMobile: {
                        required: "请填写手机号码"
                    }
                }
            });
        });

    </script>
</head>
<body>
<div class="container" style="border: 1px solid #CCCCCC;height: 1000px;">
    <div style="height:100px;border-bottom: 1px solid #CCCCCC;padding-top:30px;margin-bottom: 20px">
        <h2 class="h2">用户编辑</h2>
    </div>
    <form class="form-horizontal" role="form" id="orderForm" method="post" action="admin/order/update">
        <input type="hidden" name="orderId" value="${orderCustom.order.orderId}">
        <div class="form-group">
            <label for="orderId" class="col-sm-2 control-label">订单号：</label>
            <div class="col-sm-5">
                <span id="orderId">${orderCustom.order.orderId}</span>
            </div>
            <span></span>
        </div>
        <div class="form-group">
            <label for="username" class="col-sm-2 control-label">买家用户名：</label>
            <div class="col-sm-5">
                <span id="username">${buyer.username}</span>
            </div>
            <span></span>
        </div>
        <div class="form-group">
            <label for="payment" class="col-sm-2 control-label">商品总价：</label>
            <div class="col-sm-5">
                <span id="payment" class="red">￥${orderCustom.order.payment}</span>
            </div>
            <span></span>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">支付类型</label>
            <div class="col-sm-5">
                <c:if test="${orderCustom.order.status == 0}">
                    <span>未付款</span>
                </c:if>

                <c:if test="${orderCustom.order.status != 0}">
                    <c:if test="${orderCustom.order.paymentType == 1}">
                        <span>微信</span>
                    </c:if>
                    <c:if test="${orderCustom.order.paymentType == 2}">
                        <span>支付宝</span>
                    </c:if>
                </c:if>
            </div>
        </div>
        <div class="form-group">
            <label for="postFee" class="col-sm-2 control-label">邮费：</label>
            <div class="col-sm-5">
                <span id="postFee">${orderCustom.order.postFee}</span>
            </div>
            <span></span>
        </div>


        <div class="form-group">
            <label for="createTime" class="col-sm-2 control-label">下单时间：</label>
            <div class="col-sm-5">
                <span id="createTime"><fmt:formatDate value="${orderCustom.order.createTime}" pattern="yyyy-MM-dd"/></span>
            </div>
            <span></span>
        </div>

        <div class="form-group">
            <label for="shippingName" class="col-sm-2 control-label">快递：</label>
            <div class="col-sm-5">
                <select name="shippingName" id="shippingName">
                    <option value="圆通" ${orderCustom.order.shippingName eq "圆通"? "selected":""}>圆通</option>
                    <option value="中通" ${orderCustom.order.shippingName eq "中通"? "selected":""}>中通</option>
                    <option value="顺丰" ${orderCustom.order.shippingName eq "顺丰"? "selected":""}>顺丰</option>
                    <option value="申通" ${orderCustom.order.shippingName eq "申通"? "selected":""}>申通</option>
                </select>
            </div>
            <span></span>
        </div>


        <div class="form-group">
            <label for="receiverName" class="col-sm-2 control-label">收件人姓名：</label>
            <div class="col-sm-5">
                <input type="text" class="form-control" name="receiverName" id="receiverName" value="${orderCustom.orderShipping.receiverName}" placeholder="收件人姓名">
            </div>
            <span></span>
        </div>

        <div class="form-group">
            <label for="receiverMobile" class="col-sm-2 control-label">收件人手机号：</label>
            <div class="col-sm-5">
                <input type="text" class="form-control" name="receiverMobile" id="receiverMobile" value="${orderCustom.orderShipping.receiverMobile}" placeholder="收件人手机号">
            </div>
            <span></span>
        </div>

        <div class="form-group">
            <label for="receiverAddress" class="col-sm-2 control-label">收货地址：</label>
            <div class="col-sm-5">
                <input type="text" class="form-control" name="receiverAddress" id="receiverAddress" value="${orderCustom.orderShipping.receiverAddress}" placeholder="收货地址">
            </div>
            <span></span>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">保存订单信息</button>
                <span class="red">${saveMsg}</span>
            </div>
        </div>

    </form>
</div>
</body>
</html>

src/main/webapp/WEB-INF/jsp/admin/order/list.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<% String path = request.getContextPath();
    String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + path + "/"; %>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>订单列表</title>
    <base href="<%=basePath%>">
    <script type="text/javascript" src="js/jquery-1.11.3.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.js"></script>
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/bs.css"/>
</head>
<script type="text/javascript">

    $(function (){
        $('[data-toggle="popover"]').each(function () {
            var element = $(this);
            var buyerId = element.attr('value');
            $.ajax({
                type:"GET",
                url:"admin/order/buyer/"+buyerId,
                success : function(result){
                    if(result.code == 200){
                        element.popover({
                            trigger: 'manual',
                            placement: 'right', //top, bottom, left or right
                            title: "买家:"+result.data.username,
                            html: 'true',
                            content: "来自:"+result.data.location
                        }).on("mouseenter", function () {
                            var _this = this;
                            $(this).popover("show");
                            $(this).siblings(".popover").on("mouseleave", function () {
                                $(_this).popover('hide');
                            });
                        }).on("mouseleave", function () {
                            var _this = this;
                            setTimeout(function () {
                                if (!$(".popover:hover").length) {
                                    $(_this).popover("hide")
                                }
                            }, 100);
                        });
                    }
                },
                dataType : "json"
            });

        });
    });

    function deleteOrder(orderId) {
        if (confirm("确认删除订单吗?")) {
            location.href = "<%=basePath%>admin/order/deletion/" + orderId;
        }
    }
    function lookShipping() {
        alert("暂无物流信息!");
    }

    function postOrder(orderId) {
        if (confirm("确认发货吗?")) {
            location.href = "<%=basePath%>admin/order/post/" + orderId;
        }
    }
    
    function toEditOrder(orderId) {
        location.href = "<%=basePath%>admin/order/toUpdate/" + orderId;
    }

</script>
<body>
<div class="container" style="border: 1px solid #CCCCCC;height: 1000px;">

    <div style="height:100px;border-bottom: 1px solid #CCCCCC;padding-top:30px;margin-bottom: 10px">
        <h2 class="h2">订单列表</h2>
    </div>

    <table class="table table-hover">
        <caption>订单列表</caption>
        <thead>
        <tr>
            <th>序号</th>
            <th>订单编号</th>
            <th>商品信息</th>
            <th>订单状态</th>
            <th>金额</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        <c:forEach items="${orderCustoms}" var="orderCustom" varStatus="vs">
            <tr>
                <td>${vs.count}</td>
                <td>${orderCustom.order.orderId}</td>
                <td width="300px">
                    <c:forEach items="${orderCustom.orderDetails}" var="orderDetail">
                        <span>${orderDetail.mount}&nbsp;x</span>
                        <a href="book/info/${orderDetail.bookId}" title="${orderDetail.bookName}" target="_blank"><img src="${orderDetail.imageUrl}" width="20%"/></a>
                    </c:forEach>
                </td>
                <td>${orderCustom.order.statusString}</td>
                <td class="red">￥${orderCustom.order.payment}</td>
                <td>
                    <button type="button" class="btn btn-xs btn-info" onclick="toEditOrder('${orderCustom.order.orderId}')" >
                        查看订单
                    </button>
                    <c:if test="${orderCustom.order.status == 0}">
                        <button type="button" class="btn btn-xs btn-danger" onclick="deleteOrder('${orderCustom.order.orderId}')">
                            取消订单
                        </button>
                    </c:if>
                    <button type="button" id="buyerInfo" class="btn btn-xs btn-warning buyerInfo"
                            data-container="body" data-toggle="popover"

                            value="${orderCustom.order.userId}" <%--onclick="findBuyerInfo(${orderCustom.order.userId})"--%>>
                        买家信息
                    </button>
                    <c:if test="${orderCustom.order.status != 0}">
                        <c:if test="${orderCustom.order.status < 3}">
                            <button type="button" class="btn btn-xs btn-info" onclick="postOrder('${orderCustom.order.orderId}')" >
                                发货
                            </button>
                        </c:if>
                        <button type="button" class="btn btn-xs btn-info" onclick="lookShipping()" >
                            查看物流
                        </button>
                        <button type="button" class="btn btn-xs btn-danger" onclick="deleteOrder('${orderCustom.order.orderId}')">
                            删除订单
                        </button>
                    </c:if>
                </td>
            </tr>
        </c:forEach>
        </tbody>
    </table>

</div>

</body>
</html>